image: docker:latest

services:
  - docker:dind

stages:
  - build
  
variables:
  IMAGE_LATEST_VERSION: "9.6"

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:latest" ./$IMAGE_LATEST_VERSION/
    - docker tag "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE:$IMAGE_LATEST_VERSION"
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_LATEST_VERSION"
  tags:
    - docker
  only:
    - tags
